# Generated by Django 5.0 on 2023-12-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_payment_status_booking_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='title',
            field=models.CharField(choices=[('none', 'None'), ('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss')], default='none', max_length=5),
        ),
    ]
