# Generated by Django 5.0 on 2024-01-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='title',
        ),
    ]
