# Generated by Django 5.0 on 2024-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(),
        ),
    ]
