# Generated by Django 5.0 on 2023-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('it', 'IT')], max_length=20, null=True),
        ),
    ]
